name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '3.0'
          - '3.1'
          - '3.2'
    name: Ruby ${{ matrix.ruby }}
    continue-on-error: ${{ matrix.ruby == 'head' }}
    steps:
      - uses: actions/checkout@v2
      - name: apt-get install
        run: |
          sudo apt-get update && sudo apt-get install libcurl4 libcurl3-gnutls libcurl4-openssl-dev -y
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake
